{% set name = "nystrom-attention" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nystrom-attention-{{ version }}.tar.gz
  sha256: e012be353abd695e0e632380d9d2b66e37376a9de4b6f8ee1fd6cda3022d06f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.7.0
    - pytorch >=2.0

test:
  imports:
    - nystrom_attention
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/nystrom-attention
  summary: Nystrom Attention - Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
