{% set name = "nystrom-attention" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nystrom-attention-{{ version }}.tar.gz
  sha256: e012be353abd695e0e632380d9d2b66e37376a9de4b6f8ee1fd6cda3022d06f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - einops >=0.3
    - pytorch >=1.6

test:
  imports:
    - nystrom_attention
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucidrains/nystrom-attention
  summary: Nystrom Attention - Pytorch
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
